# Generated by Django 2.2.27 on 2022-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
